#easy_admin:
#    entities:
#        # List the entity class name you want to manage
#        - App\Entity\Product
#        - App\Entity\Category
#        - App\Entity\User

imports:
  - { resource: admin/ }

easy_admin:
  site_name: 'JOB'
  user:
    name_property_path: 'full_name'
  design:
    assets:
      css:
        - 'bundles/easyadmin/bootstrap-all.css'
      js:
        # By default, EasyAdminBundle embeds a limited version of Bootstrap JS.
        # For collapsible form filters to work, a full version should be added:
        - 'bundles/easyadmin/bootstrap-all.js'



